<script>
    import {goto} from "$app/navigation";
</script>
<div class="h-fit w-full bg-surface flex items-center justify-center">
    <div class="h-screen w-fit p-5 flex flex-col items-center justify-center">
        <p class="brand-font text-8xl w-full text-primary text-left">DISCLAIMER!</p>
        <p class="brand-font text-3xl w-full text-primary text-left">COME BACK TO THIS PAGE AFTER YOU HAVE COMPLETED
            YOUR PAYMENT</p>
        <ul class="list-disc marker:text-primary text-2xl p-5">
            <li>
                <p class="regular-font text-xl text-on-surface text-left mt-7">Come back to this page after payment and
                    click on refresh payment status</p>
            </li>
            <li>
                <p class="regular-font text-xl text-on-surface text-left">Your pass will be automatically generated by
                    clicking on the button</p>
            </li>
            <li>
                <p class="regular-font text-xl text-on-surface text-left">Just to be safe make sure to take a
                    screenshot
                    of the
                    final payment screen and save the receipt.</p>
            </li>
            <li>
                <p class="regular-font text-xl text-on-surface text-left">We are sorry for this inconvenience.</p>
            </li>
            <li>
                <p class="regular-font text-xl text-on-surface text-left">Also make sure to enter the same details
                    as
                    entered on the fests website.</p>
            </li>
        </ul>
        <button class="w-full h-fit bg-primary py-1 brand-font text-3xl text-on-primary flex items-center justify-center"
                on:click={() => {
            window.open('https://payment.manipal.edu/Tech-solstice-nexus-Login', '_blank');
            goto('/payment/manipal-dumb-check');
        }}>
            Continue
        </button>
    </div>
</div>